import {
	CharacterPattern,
	FontDefinition,
	FontStyle,
	CharForm,
	ProcessedCharacter,
	KerningDefinition,
} from '../types';

/** Standard space character for character separation */
export const SPACE = '  ';
/** Half space character for fine spacing adjustments */
export const HALF_SPACE = ' ';
/** Height of each character pattern in rows */
export const CHAR_HEIGHT = 13;

/**
 * Default kerning values (zero for both left and right)
 */
const DEFAULT_KERNING: KerningDefinition = {
	left: 0,
	right: 0,
};

/**
 * Standard Persian font with traditional block character designs
 */
const standardFont: FontDefinition = {
	ا: {
		[CharForm.ISOLATED]: {
			pattern: [
				'  ',
				'  ',
				'  ',
				'██',
				'██',
				'██',
				'██',
				'██',
				'  ',
				'  ',
				'  ',
				'  ',
				'  ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'  ',
				'  ',
				'  ',
				'██',
				'██',
				'██',
				'██',
				'██',
				'  ',
				'  ',
				'  ',
				'  ',
				'  ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'  ',
				'  ',
				'  ',
				'██',
				'██',
				'██',
				'██',
				'██',
				'  ',
				'  ',
				'  ',
				'  ',
				'  ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'  ',
				'  ',
				'  ',
				'██',
				'██',
				'██',
				'██',
				'██',
				'  ',
				'  ',
				'  ',
				'  ',
				'  ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	آ: {
		[CharForm.ISOLATED]: {
			pattern: [
				'        ',
				'████████',
				'█       ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'        ',
				'████████',
				'█       ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'        ',
				'████████',
				'█       ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'        ',
				'████████',
				'█       ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'   ██   ',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ب: {
		[CharForm.ISOLATED]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'█         █',
				'███████████',
				'           ',
				'     █     ',
				'           ',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'    █',
				'█████',
				'     ',
				'  █  ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'    █',
				'█████',
				'     ',
				'  █  ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'█         █',
				'███████████',
				'           ',
				'     █     ',
				'           ',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	پ: {
		[CharForm.ISOLATED]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'█         █',
				'███████████',
				'           ',
				'    █ █    ',
				'     █     ',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'    █',
				'█████',
				'     ',
				' █ █ ',
				'  █  ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'    █',
				'█████',
				'     ',
				' █ █ ',
				'  █  ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'█         █',
				'███████████',
				'           ',
				'    █ █    ',
				'     █     ',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ت: {
		[CharForm.ISOLATED]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'           ',
				'    █ █    ',
				'           ',
				'█         █',
				'███████████',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				' █ █ ',
				'     ',
				'    █',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				' █ █ ',
				'     ',
				'    █',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'           ',
				'    █ █    ',
				'           ',
				'█         █',
				'███████████',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ث: {
		[CharForm.ISOLATED]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'     █     ',
				'    █ █    ',
				'           ',
				'█         █',
				'███████████',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'  █  ',
				' █ █ ',
				'     ',
				'    █',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'  █  ',
				' █ █ ',
				'     ',
				'    █',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'     █     ',
				'    █ █    ',
				'           ',
				'█         █',
				'███████████',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ج: {
		[CharForm.ISOLATED]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'█       ',
				'█   █   ',
				'█       ',
				'█▅▅▅▅▅▅█',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'        ',
				'    █   ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'        ',
				'    █   ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'█       ',
				'█   █   ',
				'█       ',
				'█▅▅▅▅▅▅█',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	چ: {
		[CharForm.ISOLATED]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'█       ',
				'█  █ █  ',
				'█   █   ',
				'█▅▅▅▅▅▅█',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'        ',
				'   █ █  ',
				'    █   ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'        ',
				'   █ █  ',
				'    █   ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'       █',
				'████████',
				'█       ',
				'█  █ █  ',
				'█   █   ',
				'█▅▅▅▅▅▅█',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ح: {
		[CharForm.ISOLATED]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'█       ',
				'█       ',
				'█       ',
				'█▅▅▅▅▅▅█',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'█       ',
				'█       ',
				'█       ',
				'█▅▅▅▅▅▅█',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	خ: {
		[CharForm.ISOLATED]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'     █  ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'█       ',
				'█       ',
				'█       ',
				'█▅▅▅▅▅▅█',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'     █  ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'     █  ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'     █  ',
				'        ',
				'  ██████',
				'      ██',
				'████████',
				'█       ',
				'█       ',
				'█       ',
				'█▅▅▅▅▅▅█',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	د: {
		[CharForm.ISOLATED]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				' ████',
				'   ██',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				' ████',
				'   ██',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				' ████',
				'   ██',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				' ████',
				'   ██',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ذ: {
		[CharForm.ISOLATED]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'   █ ',
				'     ',
				' ████',
				'   ██',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'   █ ',
				'     ',
				' ████',
				'   ██',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'   █ ',
				'     ',
				' ████',
				'   ██',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'   █ ',
				'     ',
				' ████',
				'   ██',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ر: {
		[CharForm.ISOLATED]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ز: {
		[CharForm.ISOLATED]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'   █',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'   █',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'   █',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				'   █',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ژ: {
		[CharForm.ISOLATED]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'  █ ',
				'    ',
				' █ █',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'  █ ',
				'    ',
				' █ █',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'  █ ',
				'    ',
				' █ █',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'  █ ',
				'    ',
				' █ █',
				'    ',
				'  ██',
				'  ██',
				'████',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	س: {
		[CharForm.ISOLATED]: {
			pattern: [
				'              ',
				'              ',
				'              ',
				'              ',
				'              ',
				'              ',
				'█    █   █   █',
				'█    █████████',
				'█    █        ',
				'██████        ',
				'              ',
				'              ',
				'              ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
				'   █   █   █',
				'████████████',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
				'   █   █   █',
				'████████████',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'              ',
				'              ',
				'              ',
				'              ',
				'              ',
				'              ',
				'█    █   █   █',
				'█    █████████',
				'█    █        ',
				'██████        ',
				'              ',
				'              ',
				'              ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ش: {
		[CharForm.ISOLATED]: {
			pattern: [
				'              ',
				'              ',
				'              ',
				'          █   ',
				'         █ █  ',
				'              ',
				'█    █   █   █',
				'█    █████████',
				'█    █        ',
				'██████        ',
				'              ',
				'              ',
				'              ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'            ',
				'            ',
				'            ',
				'       █    ',
				'      █ █   ',
				'            ',
				'   █   █   █',
				'████████████',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'            ',
				'            ',
				'            ',
				'       █    ',
				'      █ █   ',
				'            ',
				'   █   █   █',
				'████████████',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'              ',
				'              ',
				'              ',
				'          █   ',
				'         █ █  ',
				'              ',
				'█    █   █   █',
				'█    █████████',
				'█    █        ',
				'██████        ',
				'              ',
				'              ',
				'              ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ص: {
		[CharForm.ISOLATED]: {
			pattern: [
				'              ',
				'              ',
				'              ',
				'              ',
				'              ',
				'         █████',
				'█    █   █   █',
				'█    █████████',
				'█    █        ',
				'██████        ',
				'              ',
				'              ',
				'              ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
				'       █████',
				'   █   █   █',
				'████████████',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
				'       █████',
				'   █   █   █',
				'████████████',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'              ',
				'              ',
				'              ',
				'              ',
				'              ',
				'         █████',
				'█    █   █   █',
				'█    █████████',
				'█    █        ',
				'██████        ',
				'              ',
				'              ',
				'              ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ض: {
		[CharForm.ISOLATED]: {
			pattern: [
				'              ',
				'              ',
				'              ',
				'           █  ',
				'              ',
				'         █████',
				'█    █   █   █',
				'█    █████████',
				'█    █        ',
				'██████        ',
				'              ',
				'              ',
				'              ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'            ',
				'            ',
				'            ',
				'         █  ',
				'            ',
				'       █████',
				'   █   █   █',
				'████████████',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'            ',
				'            ',
				'            ',
				'         █  ',
				'            ',
				'       █████',
				'   █   █   █',
				'████████████',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'              ',
				'              ',
				'              ',
				'           █  ',
				'              ',
				'         █████',
				'█    █   █   █',
				'█    █████████',
				'█    █        ',
				'██████        ',
				'              ',
				'              ',
				'              ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ط: {
		[CharForm.ISOLATED]: {
			pattern: [
				'         ',
				'         ',
				'         ',
				'  █      ',
				'  █      ',
				'  ███████',
				'  █     █',
				'█████████',
				'         ',
				'         ',
				'         ',
				'         ',
				'         ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'         ',
				'         ',
				'         ',
				'  █      ',
				'  █      ',
				'  ███████',
				'  █     █',
				'█████████',
				'         ',
				'         ',
				'         ',
				'         ',
				'         ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'         ',
				'         ',
				'         ',
				'  █      ',
				'  █      ',
				'  ███████',
				'  █     █',
				'█████████',
				'         ',
				'         ',
				'         ',
				'         ',
				'         ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'         ',
				'         ',
				'         ',
				'  █      ',
				'  █      ',
				'  ███████',
				'  █     █',
				'█████████',
				'         ',
				'         ',
				'         ',
				'         ',
				'         ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ظ: {
		[CharForm.ISOLATED]: {
			pattern: [
				'         ',
				'         ',
				'         ',
				'  █   █  ',
				'  █      ',
				'  ███████',
				'  █     █',
				'█████████',
				'         ',
				'         ',
				'         ',
				'         ',
				'         ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'         ',
				'         ',
				'         ',
				'  █   █  ',
				'  █      ',
				'  ███████',
				'  █     █',
				'█████████',
				'         ',
				'         ',
				'         ',
				'         ',
				'         ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'         ',
				'         ',
				'         ',
				'  █   █  ',
				'  █      ',
				'  ███████',
				'  █     █',
				'█████████',
				'         ',
				'         ',
				'         ',
				'         ',
				'         ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'         ',
				'         ',
				'         ',
				'  █   █  ',
				'  █      ',
				'  ███████',
				'  █     █',
				'█████████',
				'         ',
				'         ',
				'         ',
				'         ',
				'         ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ع: {
		[CharForm.ISOLATED]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'    ████',
				'    █   ',
				'████████',
				'█       ',
				'█       ',
				'█       ',
				'█      █',
				'████████',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'    ████',
				'    █   ',
				'████████',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'    ████',
				'    █   ',
				'████████',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'    ████',
				'    █   ',
				'████████',
				'█       ',
				'█       ',
				'█       ',
				'█      █',
				'████████',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	غ: {
		[CharForm.ISOLATED]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'      █ ',
				'        ',
				'    ████',
				'    █   ',
				'████████',
				'█       ',
				'█       ',
				'█       ',
				'█      █',
				'████████',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'      █ ',
				'        ',
				'    ████',
				'    █   ',
				'████████',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'      █ ',
				'        ',
				'    ████',
				'    █   ',
				'████████',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'      █ ',
				'        ',
				'    ████',
				'    █   ',
				'████████',
				'█       ',
				'█       ',
				'█       ',
				'█      █',
				'████████',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ف: {
		[CharForm.ISOLATED]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'         █ ',
				'           ',
				'        ███',
				'█       █ █',
				'███████████',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'   █ ',
				'     ',
				'  ███',
				'  █ █',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'   █ ',
				'     ',
				'  ███',
				'  █ █',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'         █ ',
				'           ',
				'        ███',
				'█       █ █',
				'███████████',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ق: {
		[CharForm.ISOLATED]: {
			pattern: [
				'         ',
				'         ',
				'         ',
				'      █ █',
				'         ',
				'      ███',
				'█     █ █',
				'█       █',
				'█████████',
				'         ',
				'         ',
				'         ',
				'         ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'  █ █',
				'     ',
				'  ███',
				'  █ █',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'  █ █',
				'     ',
				'  ███',
				'  █ █',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'         ',
				'         ',
				'         ',
				'      █ █',
				'         ',
				'      ███',
				'█     █ █',
				'█       █',
				'█████████',
				'         ',
				'         ',
				'         ',
				'         ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ک: {
		[CharForm.ISOLATED]: {
			pattern: [
				'            ',
				'            ',
				'            ',
				'       █████',
				'       █    ',
				'       █████',
				'█          █',
				'████████████',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'   █████',
				'   █    ',
				'   █████',
				'       █',
				'████████',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'          ',
				'          ',
				'          ',
				'     █████',
				'     █    ',
				'     █████',
				'         █',
				'██████████',
				'          ',
				'          ',
				'          ',
				'          ',
				'          ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'          ',
				'          ',
				'          ',
				'     █████',
				'     █    ',
				'     █████',
				'█        █',
				'██████████',
				'          ',
				'          ',
				'          ',
				'          ',
				'          ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	گ: {
		[CharForm.ISOLATED]: {
			pattern: [
				'            ',
				'            ',
				'       ▀▀▀▀▀',
				'       █████',
				'       █    ',
				'       █████',
				'█          █',
				'████████████',
				'            ',
				'            ',
				'            ',
				'            ',
				'            ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'        ',
				'        ',
				'   ▀▀▀▀▀',
				'   █████',
				'   █    ',
				'   █████',
				'       █',
				'████████',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'          ',
				'          ',
				'     ▀▀▀▀▀',
				'     █████',
				'     █    ',
				'     █████',
				'         █',
				'██████████',
				'          ',
				'          ',
				'          ',
				'          ',
				'          ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'          ',
				'          ',
				'     ▀▀▀▀▀',
				'     █████',
				'     █    ',
				'     █████',
				'█        █',
				'██████████',
				'          ',
				'          ',
				'          ',
				'          ',
				'          ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ل: {
		[CharForm.ISOLATED]: {
			pattern: [
				'      ',
				'      ',
				'      ',
				'    ██',
				'    ██',
				'    ██',
				'    ██',
				'█   ██',
				'█   ██',
				'██████',
				'      ',
				'      ',
				'      ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'   ██',
				'   ██',
				'   ██',
				'   ██',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'   ██',
				'   ██',
				'   ██',
				'   ██',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'      ',
				'      ',
				'      ',
				'    ██',
				'    ██',
				'    ██',
				'    ██',
				'█   ██',
				'█   ██',
				'██████',
				'      ',
				'      ',
				'      ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	م: {
		[CharForm.ISOLATED]: {
			pattern: [
				'      ',
				'      ',
				'      ',
				'      ',
				'      ',
				'   ███',
				'   █ █',
				'██████',
				'█     ',
				'█     ',
				'█     ',
				'█     ',
				'      ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'      ',
				'      ',
				'      ',
				'      ',
				'      ',
				'   ███',
				'   █ █',
				'██████',
				'      ',
				'      ',
				'      ',
				'      ',
				'      ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'      ',
				'      ',
				'      ',
				'      ',
				'      ',
				'   ███',
				'   █ █',
				'██████',
				'      ',
				'      ',
				'      ',
				'      ',
				'      ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'      ',
				'      ',
				'      ',
				'      ',
				'      ',
				'   ███',
				'   █ █',
				'██████',
				'█     ',
				'█     ',
				'█     ',
				'█     ',
				'      ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ن: {
		[CharForm.ISOLATED]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'█    █    █',
				'█         █',
				'█         █',
				'███████████',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'  █  ',
				'     ',
				'    █',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'  █  ',
				'     ',
				'    █',
				'█████',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'█    █    █',
				'█         █',
				'█         █',
				'███████████',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	و: {
		[CharForm.ISOLATED]: {
			pattern: [
				'   ',
				'   ',
				'   ',
				'   ',
				'   ',
				'███',
				'█ █',
				'███',
				'  █',
				'███',
				'   ',
				'   ',
				'   ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'   ',
				'   ',
				'   ',
				'   ',
				'   ',
				'███',
				'█ █',
				'███',
				'  █',
				'███',
				'   ',
				'   ',
				'   ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'   ',
				'   ',
				'   ',
				'   ',
				'   ',
				'███',
				'█ █',
				'███',
				'  █',
				'███',
				'   ',
				'   ',
				'   ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'   ',
				'   ',
				'   ',
				'   ',
				'   ',
				'███',
				'█ █',
				'███',
				'  █',
				'███',
				'   ',
				'   ',
				'   ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ه: {
		[CharForm.ISOLATED]: {
			pattern: [
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
				' ██ ',
				'█  █',
				'████',
				'    ',
				'    ',
				'    ',
				'    ',
				'    ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
				'   █████',
				'   █ █ █',
				'████████',
				'        ',
				'        ',
				'        ',
				'        ',
				'        ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'       ',
				'       ',
				'       ',
				'       ',
				'       ',
				'  ███  ',
				'  █ █  ',
				'███████',
				'  █ █  ',
				'  ███  ',
				'       ',
				'       ',
				'       ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'         ',
				'         ',
				'         ',
				'         ',
				'████     ',
				'█  █     ',
				'████     ',
				'  ███████',
				'         ',
				'         ',
				'         ',
				'         ',
				'         ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	ی: {
		[CharForm.ISOLATED]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'█    ██████',
				'█    █▃▃▃▃▃',
				'█         █',
				'███████████',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'    █',
				'█████',
				'     ',
				' █ █ ',
				'     ',
				'     ',
				'     ',
			],
			kerning: {
				right: -2,
				left: 0,
			},
		},
		[CharForm.MEDIAL]: {
			pattern: [
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'     ',
				'    █',
				'█████',
				'     ',
				' █ █ ',
				'     ',
				'     ',
				'     ',
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'           ',
				'█    ██████',
				'█    █▃▃▃▃▃',
				'█         █',
				'███████████',
				'           ',
				'           ',
			],
			kerning: DEFAULT_KERNING,
		},
	},
	' ': {
		[CharForm.ISOLATED]: {
			pattern: [
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
				SPACE,
			],
			kerning: DEFAULT_KERNING,
		},
	},
	__HALF_SPACE__: {
		[CharForm.ISOLATED]: {
			pattern: [
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.INITIAL]: {
			pattern: [
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.MEDIAL]: {
			pattern: [
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
			],
			kerning: DEFAULT_KERNING,
		},
		[CharForm.FINAL]: {
			pattern: [
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
				HALF_SPACE,
			],
			kerning: DEFAULT_KERNING,
		},
	},
};

/**
 * Collection of all available fonts
 */
const fonts: Record<FontStyle, FontDefinition> = {
	[FontStyle.STANDARD]: standardFont,
};

/**
 * Get pattern for a character and form from specified font, with fallback
 * @param char - The character to get pattern for
 * @param form - The char form to use
 * @param fontStyle - The font style to use
 * @returns Array of strings representing the character pattern
 */
export function getPattern(
	char: string,
	form: CharForm,
	fontStyle: FontStyle = FontStyle.STANDARD,
): CharacterPattern {
	const font = fonts[fontStyle];
	const charPatterns = font[char];

	if (charPatterns && charPatterns[form]) {
		return charPatterns[form].pattern;
	}

	// Fallback to isolated form or space pattern
	if (charPatterns && charPatterns[CharForm.ISOLATED]) {
		return charPatterns[CharForm.ISOLATED].pattern;
	}

	return font[' '][CharForm.ISOLATED].pattern;
}

/**
 * Persian chars that don't connect to the following char
 */
export const NON_CONNECTING_CHARS = new Set([
	'ا',
	'د',
	'ذ',
	'ر',
	'ز',
	'ژ',
	'و',
	'آ',
]);

/**
 * Check if a character is a Persian/Arabic char
 * @param char - Character to check
 * @returns True if the character is a Persian/Arabic char
 */
export function isPersianChar(char: string): boolean {
	if (!char) return false;
	const code = char.charCodeAt(0);

	// Persian chars and Arabic block
	const isArabicBase = code >= 0x0600 && code <= 0x06ff;
	// Persian digits (۰–۹)
	const isPersianDigit = code >= 0x06f0 && code <= 0x06f9;

	return isArabicBase || isPersianDigit;
}

/**
 * Check if a char can connect to the next char
 * @param char - Character to check
 * @returns True if the character can connect to the next char
 */
export function canConnectToNext(char: string): boolean {
	return isPersianChar(char) && !NON_CONNECTING_CHARS.has(char);
}

/**
 * Check if a char can connect to the previous char
 * @param char - Character to check
 * @returns True if the character can connect to the previous char
 */
export function canConnectToPrev(char: string): boolean {
	return isPersianChar(char);
}

/**
 * Process a string of Persian text and return an array of characters with their forms
 * @param text - Persian text to process
 * @returns Array of processed characters with their determined forms
 */
export function processText(text: string): ProcessedCharacter[] {
	const result: ProcessedCharacter[] = [];
	const chars = text.split('');

	for (let i = 0; i < chars.length; i++) {
		const currentChar = chars[i];
		const prevChar = i > 0 ? chars[i - 1] : null;
		const nextChar = i < chars.length - 1 ? chars[i + 1] : null;

		// Treat zero-width non-joiner as a break: push a space placeholder
		if (currentChar === '\u200C') {
			result.push({char: '__HALF_SPACE__', form: CharForm.ISOLATED});
			continue;
		}

		// Skip non-Persian characters (spaces, punctuation, etc.)
		if (!isPersianChar(currentChar)) {
			result.push({char: currentChar, form: CharForm.ISOLATED});
			continue;
		}

		// Determine if current char connects to previous
		const connectsToPrev =
			prevChar &&
			canConnectToPrev(currentChar) &&
			canConnectToNext(prevChar) &&
			isPersianChar(prevChar);

		// Determine if current char connects to next
		const connectsToNext =
			nextChar &&
			canConnectToNext(currentChar) &&
			canConnectToPrev(nextChar) &&
			isPersianChar(nextChar);

		// Determine the form based on connections
		let form: CharForm;
		if (connectsToPrev && connectsToNext) {
			form = CharForm.MEDIAL;
		} else if (connectsToPrev && !connectsToNext) {
			form = CharForm.FINAL;
		} else if (!connectsToPrev && connectsToNext) {
			form = CharForm.INITIAL;
		} else {
			form = CharForm.ISOLATED;
		}

		result.push({char: currentChar, form});

		// implicit break: if this char cannot connect forward but next is a char
		if (
			isPersianChar(currentChar) &&
			nextChar &&
			!canConnectToNext(currentChar)
		) {
			result.push({char: '__HALF_SPACE__', form: CharForm.ISOLATED});
		}
	}

	return result;
}
