import {
	CharacterPattern,
	FontDefinition,
	FontStyle,
	LetterForm,
	ProcessedCharacter,
} from '../types';

/** Standard space character for character separation */
export const SPACE = '  ';
/** Half space character for fine spacing adjustments */
export const HALF_SPACE = ' ';
/** Height of each character pattern in rows */
export const CHAR_HEIGHT = 13;

/**
 * Standard Persian font with traditional block character designs
 */
const standardFont: FontDefinition = {
	ا: {
		[LetterForm.ISOLATED]: [
			'  ',
			'  ',
			'  ',
			'██',
			'██',
			'██',
			'██',
			'██',
			'  ',
			'  ',
			'  ',
			'  ',
			'  ',
		],
		[LetterForm.INITIAL]: [
			'  ',
			'  ',
			'  ',
			'██',
			'██',
			'██',
			'██',
			'██',
			'  ',
			'  ',
			'  ',
			'  ',
			'  ',
		],
		[LetterForm.MEDIAL]: [
			'  ',
			'  ',
			'  ',
			'██',
			'██',
			'██',
			'██',
			'██',
			'  ',
			'  ',
			'  ',
			'  ',
			'  ',
		],
		[LetterForm.FINAL]: [
			'  ',
			'  ',
			'  ',
			'██',
			'██',
			'██',
			'██',
			'██',
			'  ',
			'  ',
			'  ',
			'  ',
			'  ',
		],
	},
	آ: {
		[LetterForm.ISOLATED]: [
			'        ',
			'████████',
			'█       ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.INITIAL]: [
			'        ',
			'████████',
			'█       ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.MEDIAL]: [
			'        ',
			'████████',
			'█       ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.FINAL]: [
			'        ',
			'████████',
			'█       ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'   ██   ',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
	},
	ب: {
		[LetterForm.ISOLATED]: [
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
			'█     █',
			'███████',
			'       ',
			'   █   ',
			'       ',
			'       ',
			'       ',
		],
		[LetterForm.INITIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'    █',
			'█████',
			'     ',
			'  █  ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.MEDIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'    █',
			'█████',
			'     ',
			'  █  ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.FINAL]: [
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
			'█     █',
			'███████',
			'       ',
			'   █   ',
			'       ',
			'       ',
			'       ',
		],
	},
	پ: {
		[LetterForm.ISOLATED]: [
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
			'█     █',
			'███████',
			'       ',
			'  █ █  ',
			'   █   ',
			'       ',
			'       ',
		],
		[LetterForm.INITIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'    █',
			'█████',
			'     ',
			' █ █ ',
			'  █  ',
			'     ',
			'     ',
		],
		[LetterForm.MEDIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'    █',
			'█████',
			'     ',
			' █ █ ',
			'  █  ',
			'     ',
			'     ',
		],
		[LetterForm.FINAL]: [
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
			'█     █',
			'███████',
			'       ',
			'  █ █  ',
			'   █   ',
			'       ',
			'       ',
		],
	},
	ت: {
		[LetterForm.ISOLATED]: [
			'       ',
			'       ',
			'       ',
			'       ',
			'  █ █  ',
			'       ',
			'█     █',
			'███████',
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
		],
		[LetterForm.INITIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			' █ █ ',
			'     ',
			'    █',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.MEDIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			' █ █ ',
			'     ',
			'    █',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.FINAL]: [
			'       ',
			'       ',
			'       ',
			'       ',
			'  █ █  ',
			'       ',
			'█     █',
			'███████',
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
		],
	},
	ث: {
		[LetterForm.ISOLATED]: [
			'       ',
			'       ',
			'       ',
			'   █   ',
			'  █ █  ',
			'       ',
			'█     █',
			'███████',
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
		],
		[LetterForm.INITIAL]: [
			'     ',
			'     ',
			'     ',
			'  █  ',
			' █ █ ',
			'     ',
			'    █',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.MEDIAL]: [
			'     ',
			'     ',
			'     ',
			'  █  ',
			' █ █ ',
			'     ',
			'    █',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.FINAL]: [
			'       ',
			'       ',
			'       ',
			'   █   ',
			'  █ █  ',
			'       ',
			'█     █',
			'███████',
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
		],
	},
	ج: {
		[LetterForm.ISOLATED]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'█       ',
			'█   █   ',
			'█       ',
			'█▅▅▅▅▅▅█',
			'        ',
		],
		[LetterForm.INITIAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'        ',
			'    █   ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.MEDIAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'        ',
			'    █   ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.FINAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'█       ',
			'█   █   ',
			'█       ',
			'█▅▅▅▅▅▅█',
			'        ',
		],
	},
	چ: {
		[LetterForm.ISOLATED]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'█       ',
			'█  █ █  ',
			'█   █   ',
			'█▅▅▅▅▅▅█',
			'        ',
		],
		[LetterForm.INITIAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'        ',
			'   █ █  ',
			'    █   ',
			'        ',
			'        ',
		],
		[LetterForm.MEDIAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'        ',
			'   █ █  ',
			'    █   ',
			'        ',
			'        ',
		],
		[LetterForm.FINAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'       █',
			'████████',
			'█       ',
			'█  █ █  ',
			'█   █   ',
			'█▅▅▅▅▅▅█',
			'        ',
		],
	},
	ح: {
		[LetterForm.ISOLATED]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'█       ',
			'█       ',
			'█       ',
			'█▅▅▅▅▅▅█',
			'        ',
		],
		[LetterForm.INITIAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.MEDIAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.FINAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'█       ',
			'█       ',
			'█       ',
			'█▅▅▅▅▅▅█',
			'        ',
		],
	},
	خ: {
		[LetterForm.ISOLATED]: [
			'        ',
			'        ',
			'        ',
			'     █  ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'█       ',
			'█       ',
			'█       ',
			'█▅▅▅▅▅▅█',
			'        ',
		],
		[LetterForm.INITIAL]: [
			'        ',
			'        ',
			'        ',
			'     █  ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.MEDIAL]: [
			'        ',
			'        ',
			'        ',
			'     █  ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.FINAL]: [
			'        ',
			'        ',
			'        ',
			'     █  ',
			'        ',
			'  ██████',
			'      ██',
			'████████',
			'█       ',
			'█       ',
			'█       ',
			'█▅▅▅▅▅▅█',
			'        ',
		],
	},
	د: {
		[LetterForm.ISOLATED]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			' ████',
			'   ██',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.INITIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			' ████',
			'   ██',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.MEDIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			' ████',
			'   ██',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.FINAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			' ████',
			'   ██',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
	},
	ذ: {
		[LetterForm.ISOLATED]: [
			'     ',
			'     ',
			'     ',
			'   █ ',
			'     ',
			' ████',
			'   ██',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.INITIAL]: [
			'     ',
			'     ',
			'     ',
			'   █ ',
			'     ',
			' ████',
			'   ██',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.MEDIAL]: [
			'     ',
			'     ',
			'     ',
			'   █ ',
			'     ',
			' ████',
			'   ██',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.FINAL]: [
			'     ',
			'     ',
			'     ',
			'   █ ',
			'     ',
			' ████',
			'   ██',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
	},
	ر: {
		[LetterForm.ISOLATED]: [
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
		[LetterForm.INITIAL]: [
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
		[LetterForm.MEDIAL]: [
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
		[LetterForm.FINAL]: [
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
	},
	ز: {
		[LetterForm.ISOLATED]: [
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'   █',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
		[LetterForm.INITIAL]: [
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'   █',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
		[LetterForm.MEDIAL]: [
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'   █',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
		[LetterForm.FINAL]: [
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			'   █',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
	},
	ژ: {
		[LetterForm.ISOLATED]: [
			'    ',
			'    ',
			'    ',
			'  █ ',
			'    ',
			' █ █',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
		[LetterForm.INITIAL]: [
			'    ',
			'    ',
			'    ',
			'  █ ',
			'    ',
			' █ █',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
		[LetterForm.MEDIAL]: [
			'    ',
			'    ',
			'    ',
			'  █ ',
			'    ',
			' █ █',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
		[LetterForm.FINAL]: [
			'    ',
			'    ',
			'    ',
			'  █ ',
			'    ',
			' █ █',
			'    ',
			'  ██',
			'  ██',
			'████',
			'    ',
			'    ',
			'    ',
		],
	},
	س: {
		[LetterForm.ISOLATED]: [
			'              ',
			'              ',
			'              ',
			'              ',
			'              ',
			'              ',
			'█    █   █   █',
			'█    █████████',
			'█    █        ',
			'██████        ',
			'              ',
			'              ',
			'              ',
		],
		[LetterForm.INITIAL]: [
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
			'   █   █   █',
			'████████████',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
		],
		[LetterForm.MEDIAL]: [
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
			'   █   █   █',
			'████████████',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
		],
		[LetterForm.FINAL]: [
			'              ',
			'              ',
			'              ',
			'              ',
			'              ',
			'              ',
			'█    █   █   █',
			'█    █████████',
			'█    █        ',
			'██████        ',
			'              ',
			'              ',
			'              ',
		],
	},
	ش: {
		[LetterForm.ISOLATED]: [
			'              ',
			'              ',
			'              ',
			'          █   ',
			'         █ █  ',
			'              ',
			'█    █   █   █',
			'█    █████████',
			'█    █        ',
			'██████        ',
			'              ',
			'              ',
			'              ',
		],
		[LetterForm.INITIAL]: [
			'            ',
			'            ',
			'            ',
			'       █    ',
			'      █ █   ',
			'            ',
			'   █   █   █',
			'████████████',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
		],
		[LetterForm.MEDIAL]: [
			'            ',
			'            ',
			'            ',
			'       █    ',
			'      █ █   ',
			'            ',
			'   █   █   █',
			'████████████',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
		],
		[LetterForm.FINAL]: [
			'              ',
			'              ',
			'              ',
			'          █   ',
			'         █ █  ',
			'              ',
			'█    █   █   █',
			'█    █████████',
			'█    █        ',
			'██████        ',
			'              ',
			'              ',
			'              ',
		],
	},
	ص: {
		[LetterForm.ISOLATED]: [
			'              ',
			'              ',
			'              ',
			'              ',
			'              ',
			'         █████',
			'█    █   █   █',
			'█    █████████',
			'█    █        ',
			'██████        ',
			'              ',
			'              ',
			'              ',
		],
		[LetterForm.INITIAL]: [
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
			'       █████',
			'   █   █   █',
			'████████████',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
		],
		[LetterForm.MEDIAL]: [
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
			'       █████',
			'   █   █   █',
			'████████████',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
		],
		[LetterForm.FINAL]: [
			'              ',
			'              ',
			'              ',
			'              ',
			'              ',
			'         █████',
			'█    █   █   █',
			'█    █████████',
			'█    █        ',
			'██████        ',
			'              ',
			'              ',
			'              ',
		],
	},
	ض: {
		[LetterForm.ISOLATED]: [
			'              ',
			'              ',
			'              ',
			'           █  ',
			'              ',
			'         █████',
			'█    █   █   █',
			'█    █████████',
			'█    █        ',
			'██████        ',
			'              ',
			'              ',
			'              ',
		],
		[LetterForm.INITIAL]: [
			'            ',
			'            ',
			'            ',
			'         █  ',
			'            ',
			'       █████',
			'   █   █   █',
			'████████████',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
		],
		[LetterForm.MEDIAL]: [
			'            ',
			'            ',
			'            ',
			'         █  ',
			'            ',
			'       █████',
			'   █   █   █',
			'████████████',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
		],
		[LetterForm.FINAL]: [
			'              ',
			'              ',
			'              ',
			'           █  ',
			'              ',
			'         █████',
			'█    █   █   █',
			'█    █████████',
			'█    █        ',
			'██████        ',
			'              ',
			'              ',
			'              ',
		],
	},
	ط: {
		[LetterForm.ISOLATED]: [
			'         ',
			'         ',
			'         ',
			'  █      ',
			'  █      ',
			'  ███████',
			'  █     █',
			'█████████',
			'         ',
			'         ',
			'         ',
			'         ',
			'         ',
		],
		[LetterForm.INITIAL]: [
			'         ',
			'         ',
			'         ',
			'  █      ',
			'  █      ',
			'  ███████',
			'  █     █',
			'█████████',
			'         ',
			'         ',
			'         ',
			'         ',
			'         ',
		],
		[LetterForm.MEDIAL]: [
			'         ',
			'         ',
			'         ',
			'  █      ',
			'  █      ',
			'  ███████',
			'  █     █',
			'█████████',
			'         ',
			'         ',
			'         ',
			'         ',
			'         ',
		],
		[LetterForm.FINAL]: [
			'         ',
			'         ',
			'         ',
			'  █      ',
			'  █      ',
			'  ███████',
			'  █     █',
			'█████████',
			'         ',
			'         ',
			'         ',
			'         ',
			'         ',
		],
	},
	ظ: {
		[LetterForm.ISOLATED]: [
			'         ',
			'         ',
			'         ',
			'  █   █  ',
			'  █      ',
			'  ███████',
			'  █     █',
			'█████████',
			'         ',
			'         ',
			'         ',
			'         ',
			'         ',
		],
		[LetterForm.INITIAL]: [
			'         ',
			'         ',
			'         ',
			'  █   █  ',
			'  █      ',
			'  ███████',
			'  █     █',
			'█████████',
			'         ',
			'         ',
			'         ',
			'         ',
			'         ',
		],
		[LetterForm.MEDIAL]: [
			'         ',
			'         ',
			'         ',
			'  █   █  ',
			'  █      ',
			'  ███████',
			'  █     █',
			'█████████',
			'         ',
			'         ',
			'         ',
			'         ',
			'         ',
		],
		[LetterForm.FINAL]: [
			'         ',
			'         ',
			'         ',
			'  █   █  ',
			'  █      ',
			'  ███████',
			'  █     █',
			'█████████',
			'         ',
			'         ',
			'         ',
			'         ',
			'         ',
		],
	},
	ع: {
		[LetterForm.ISOLATED]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'    ████',
			'    █   ',
			'████████',
			'█       ',
			'█       ',
			'█       ',
			'█      █',
			'████████',
		],
		[LetterForm.INITIAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'    ████',
			'    █   ',
			'████████',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.MEDIAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'    ████',
			'    █   ',
			'████████',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.FINAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'    ████',
			'    █   ',
			'████████',
			'█       ',
			'█       ',
			'█       ',
			'█      █',
			'████████',
		],
	},
	غ: {
		[LetterForm.ISOLATED]: [
			'        ',
			'        ',
			'        ',
			'      █ ',
			'        ',
			'    ████',
			'    █   ',
			'████████',
			'█       ',
			'█       ',
			'█       ',
			'█      █',
			'████████',
		],
		[LetterForm.INITIAL]: [
			'        ',
			'        ',
			'        ',
			'      █ ',
			'        ',
			'    ████',
			'    █   ',
			'████████',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.MEDIAL]: [
			'        ',
			'        ',
			'        ',
			'      █ ',
			'        ',
			'    ████',
			'    █   ',
			'████████',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.FINAL]: [
			'        ',
			'        ',
			'        ',
			'      █ ',
			'        ',
			'    ████',
			'    █   ',
			'████████',
			'█       ',
			'█       ',
			'█       ',
			'█      █',
			'████████',
		],
	},
	ف: {
		[LetterForm.ISOLATED]: [
			'       ',
			'       ',
			'       ',
			'     █ ',
			'       ',
			'    ███',
			'█   █ █',
			'███████',
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
		],
		[LetterForm.INITIAL]: [
			'     ',
			'     ',
			'     ',
			'   █ ',
			'     ',
			'  ███',
			'  █ █',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.MEDIAL]: [
			'     ',
			'     ',
			'     ',
			'   █ ',
			'     ',
			'  ███',
			'  █ █',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.FINAL]: [
			'       ',
			'       ',
			'       ',
			'     █ ',
			'       ',
			'    ███',
			'█   █ █',
			'███████',
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
		],
	},
	ق: {
		[LetterForm.ISOLATED]: [
			'       ',
			'       ',
			'       ',
			'    █ █',
			'       ',
			'    ███',
			'█   █ █',
			'█     █',
			'███████',
			'       ',
			'       ',
			'       ',
			'       ',
		],
		[LetterForm.INITIAL]: [
			'     ',
			'     ',
			'     ',
			'  █ █',
			'     ',
			'  ███',
			'  █ █',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.MEDIAL]: [
			'     ',
			'     ',
			'     ',
			'  █ █',
			'     ',
			'  ███',
			'  █ █',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.FINAL]: [
			'       ',
			'       ',
			'       ',
			'    █ █',
			'       ',
			'    ███',
			'█   █ █',
			'█     █',
			'███████',
			'       ',
			'       ',
			'       ',
			'       ',
		],
	},
	ک: {
		[LetterForm.ISOLATED]: [
			'            ',
			'            ',
			'            ',
			'       █████',
			'       █    ',
			'       █████',
			'█          █',
			'████████████',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
		],
		[LetterForm.INITIAL]: [
			'        ',
			'        ',
			'        ',
			'   █████',
			'   █    ',
			'   █████',
			'       █',
			'████████',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.MEDIAL]: [
			'          ',
			'          ',
			'          ',
			'     █████',
			'     █    ',
			'     █████',
			'         █',
			'██████████',
			'          ',
			'          ',
			'          ',
			'          ',
			'          ',
		],
		[LetterForm.FINAL]: [
			'          ',
			'          ',
			'          ',
			'     █████',
			'     █    ',
			'     █████',
			'█        █',
			'██████████',
			'          ',
			'          ',
			'          ',
			'          ',
			'          ',
		],
	},
	گ: {
		[LetterForm.ISOLATED]: [
			'            ',
			'            ',
			'       ▀▀▀▀▀',
			'       █████',
			'       █    ',
			'       █████',
			'█          █',
			'████████████',
			'            ',
			'            ',
			'            ',
			'            ',
			'            ',
		],
		[LetterForm.INITIAL]: [
			'        ',
			'        ',
			'   ▀▀▀▀▀',
			'   █████',
			'   █    ',
			'   █████',
			'       █',
			'████████',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.MEDIAL]: [
			'          ',
			'          ',
			'     ▀▀▀▀▀',
			'     █████',
			'     █    ',
			'     █████',
			'         █',
			'██████████',
			'          ',
			'          ',
			'          ',
			'          ',
			'          ',
		],
		[LetterForm.FINAL]: [
			'          ',
			'          ',
			'     ▀▀▀▀▀',
			'     █████',
			'     █    ',
			'     █████',
			'█        █',
			'██████████',
			'          ',
			'          ',
			'          ',
			'          ',
			'          ',
		],
	},
	ل: {
		[LetterForm.ISOLATED]: [
			'      ',
			'      ',
			'      ',
			'    ██',
			'    ██',
			'    ██',
			'    ██',
			'█   ██',
			'█   ██',
			'██████',
			'      ',
			'      ',
			'      ',
		],
		[LetterForm.INITIAL]: [
			'     ',
			'     ',
			'     ',
			'   ██',
			'   ██',
			'   ██',
			'   ██',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.MEDIAL]: [
			'     ',
			'     ',
			'     ',
			'   ██',
			'   ██',
			'   ██',
			'   ██',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.FINAL]: [
			'      ',
			'      ',
			'      ',
			'    ██',
			'    ██',
			'    ██',
			'    ██',
			'█   ██',
			'█   ██',
			'██████',
			'      ',
			'      ',
			'      ',
		],
	},
	م: {
		[LetterForm.ISOLATED]: [
			'      ',
			'      ',
			'      ',
			'      ',
			'      ',
			'   ███',
			'   █ █',
			'██████',
			'█     ',
			'█     ',
			'█     ',
			'█     ',
			'      ',
		],
		[LetterForm.INITIAL]: [
			'      ',
			'      ',
			'      ',
			'      ',
			'      ',
			'   ███',
			'   █ █',
			'██████',
			'      ',
			'      ',
			'      ',
			'      ',
			'      ',
		],
		[LetterForm.MEDIAL]: [
			'      ',
			'      ',
			'      ',
			'      ',
			'      ',
			'   ███',
			'   █ █',
			'██████',
			'      ',
			'      ',
			'      ',
			'      ',
			'      ',
		],
		[LetterForm.FINAL]: [
			'      ',
			'      ',
			'      ',
			'      ',
			'      ',
			'   ███',
			'   █ █',
			'██████',
			'█     ',
			'█     ',
			'█     ',
			'█     ',
			'      ',
		],
	},
	ن: {
		[LetterForm.ISOLATED]: [
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'█    █    █',
			'█         █',
			'█         █',
			'███████████',
			'           ',
			'           ',
		],
		[LetterForm.INITIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'  █  ',
			'     ',
			'    █',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.MEDIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'  █  ',
			'     ',
			'    █',
			'█████',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.FINAL]: [
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'█    █    █',
			'█         █',
			'█         █',
			'███████████',
			'           ',
			'           ',
		],
	},
	و: {
		[LetterForm.ISOLATED]: [
			'   ',
			'   ',
			'   ',
			'   ',
			'   ',
			'███',
			'█ █',
			'███',
			'  █',
			'███',
			'   ',
			'   ',
			'   ',
		],
		[LetterForm.INITIAL]: [
			'   ',
			'   ',
			'   ',
			'   ',
			'   ',
			'███',
			'█ █',
			'███',
			'  █',
			'███',
			'   ',
			'   ',
			'   ',
		],
		[LetterForm.MEDIAL]: [
			'   ',
			'   ',
			'   ',
			'   ',
			'   ',
			'███',
			'█ █',
			'███',
			'  █',
			'███',
			'   ',
			'   ',
			'   ',
		],
		[LetterForm.FINAL]: [
			'   ',
			'   ',
			'   ',
			'   ',
			'   ',
			'███',
			'█ █',
			'███',
			'  █',
			'███',
			'   ',
			'   ',
			'   ',
		],
	},
	ه: {
		[LetterForm.ISOLATED]: [
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
			' ██ ',
			'█  █',
			'████',
			'    ',
			'    ',
			'    ',
			'    ',
			'    ',
		],
		[LetterForm.INITIAL]: [
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
			'   █████',
			'   █ █ █',
			'████████',
			'        ',
			'        ',
			'        ',
			'        ',
			'        ',
		],
		[LetterForm.MEDIAL]: [
			'       ',
			'       ',
			'       ',
			'       ',
			'       ',
			'  ███  ',
			'  █ █  ',
			'███████',
			'  █ █  ',
			'  ███  ',
			'       ',
			'       ',
			'       ',
		],
		[LetterForm.FINAL]: [
			'         ',
			'         ',
			'         ',
			'         ',
			'████     ',
			'█  █     ',
			'████     ',
			'  ███████',
			'         ',
			'         ',
			'         ',
			'         ',
			'         ',
		],
	},
	ی: {
		[LetterForm.ISOLATED]: [
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'█    ██████',
			'█    █▃▃▃▃▃',
			'█         █',
			'███████████',
			'           ',
			'           ',
		],
		[LetterForm.INITIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'    █',
			'█████',
			'     ',
			' █ █ ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.MEDIAL]: [
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'     ',
			'    █',
			'█████',
			'     ',
			' █ █ ',
			'     ',
			'     ',
			'     ',
		],
		[LetterForm.FINAL]: [
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'           ',
			'█    ██████',
			'█    █▃▃▃▃▃',
			'█         █',
			'███████████',
			'           ',
			'           ',
		],
	},
	' ': {
		[LetterForm.ISOLATED]: [
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
		],
		[LetterForm.INITIAL]: [
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
		],
		[LetterForm.MEDIAL]: [
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
		],
		[LetterForm.FINAL]: [
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
			SPACE,
		],
	},
	__HALF_SPACE__: {
		[LetterForm.ISOLATED]: [
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
		],
		[LetterForm.INITIAL]: [
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
		],
		[LetterForm.MEDIAL]: [
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
		],
		[LetterForm.FINAL]: [
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
			HALF_SPACE,
		],
	},
};

/**
 * Collection of all available fonts
 */
const fonts: Record<FontStyle, FontDefinition> = {
	[FontStyle.STANDARD]: standardFont,
};

/**
 * Get pattern for a character and form from specified font, with fallback
 * @param char - The character to get pattern for
 * @param form - The letter form to use
 * @param fontStyle - The font style to use
 * @returns Array of strings representing the character pattern
 */
export function getPattern(
	char: string,
	form: LetterForm,
	fontStyle: FontStyle = FontStyle.STANDARD,
): CharacterPattern {
	const font = fonts[fontStyle];
	const charPatterns = font[char];

	if (charPatterns && charPatterns[form]) {
		return charPatterns[form];
	}

	// Fallback to isolated form or space pattern
	if (charPatterns && charPatterns[LetterForm.ISOLATED]) {
		return charPatterns[LetterForm.ISOLATED];
	}

	return font[' '][LetterForm.ISOLATED];
}

/**
 * Persian letters that don't connect to the following letter
 */
export const NON_CONNECTING_LETTERS = new Set([
	'ا',
	'د',
	'ذ',
	'ر',
	'ز',
	'ژ',
	'و',
	'آ',
]);

/**
 * Check if a character is a Persian/Arabic letter
 * @param char - Character to check
 * @returns True if the character is a Persian/Arabic letter
 */
export function isPersianLetter(char: string): boolean {
	if (!char) return false;
	const code = char.charCodeAt(0);

	// Persian letters and Arabic block
	const isArabicBase = code >= 0x0600 && code <= 0x06ff;
	// Persian digits (۰–۹)
	const isPersianDigit = code >= 0x06f0 && code <= 0x06f9;

	return isArabicBase || isPersianDigit;
}

/**
 * Check if a letter can connect to the next letter
 * @param char - Character to check
 * @returns True if the character can connect to the next letter
 */
export function canConnectToNext(char: string): boolean {
	return isPersianLetter(char) && !NON_CONNECTING_LETTERS.has(char);
}

/**
 * Check if a letter can connect to the previous letter
 * @param char - Character to check
 * @returns True if the character can connect to the previous letter
 */
export function canConnectToPrev(char: string): boolean {
	return isPersianLetter(char);
}

/**
 * Process a string of Persian text and return an array of characters with their forms
 * @param text - Persian text to process
 * @returns Array of processed characters with their determined forms
 */
export function processText(text: string): ProcessedCharacter[] {
	const result: ProcessedCharacter[] = [];
	const chars = text.split('');

	for (let i = 0; i < chars.length; i++) {
		const currentChar = chars[i];
		const prevChar = i > 0 ? chars[i - 1] : null;
		const nextChar = i < chars.length - 1 ? chars[i + 1] : null;

		// Treat zero-width non-joiner as a break: push a space placeholder
		if (currentChar === '\u200C') {
			result.push({char: '__HALF_SPACE__', form: LetterForm.ISOLATED});
			continue;
		}

		// Skip non-Persian characters (spaces, punctuation, etc.)
		if (!isPersianLetter(currentChar)) {
			result.push({char: currentChar, form: LetterForm.ISOLATED});
			continue;
		}

		// Determine if current letter connects to previous
		const connectsToPrev =
			prevChar &&
			canConnectToPrev(currentChar) &&
			canConnectToNext(prevChar) &&
			isPersianLetter(prevChar);

		// Determine if current letter connects to next
		const connectsToNext =
			nextChar &&
			canConnectToNext(currentChar) &&
			canConnectToPrev(nextChar) &&
			isPersianLetter(nextChar);

		// Determine the form based on connections
		let form: LetterForm;
		if (connectsToPrev && connectsToNext) {
			form = LetterForm.MEDIAL;
		} else if (connectsToPrev && !connectsToNext) {
			form = LetterForm.FINAL;
		} else if (!connectsToPrev && connectsToNext) {
			form = LetterForm.INITIAL;
		} else {
			form = LetterForm.ISOLATED;
		}

		result.push({char: currentChar, form});

		// implicit break: if this char cannot connect forward but next is a letter
		if (
			isPersianLetter(currentChar) &&
			nextChar &&
			!canConnectToNext(currentChar)
		) {
			result.push({char: '__HALF_SPACE__', form: LetterForm.ISOLATED});
		}
	}

	return result;
}
